package com.onnx.lirufiru.app.components;

import java.text.DecimalFormat;

import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame {

    double dTx = 0.0, sTx = 0.0, hTx = 0.0, lTx = 0.0, zTx = 0.0, sigTx = 0.0, qTx = 0.0, tTx = 0.0;
    int tD = 1, tH = 1;

    /**
     * Creates new form GUI
     */
    public GUI() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanel = new javax.swing.JTabbedPane();
        pPOQ = new javax.swing.JPanel();
        jlQ = new javax.swing.JLabel();
        tfQ = new javax.swing.JTextField();
        cbQ = new javax.swing.JCheckBox();
        jlD = new javax.swing.JLabel();
        tfD = new javax.swing.JTextField();
        cbD = new javax.swing.JComboBox<>();
        jlS = new javax.swing.JLabel();
        tfS = new javax.swing.JTextField();
        jlH = new javax.swing.JLabel();
        tfH = new javax.swing.JTextField();
        cbH = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        jpPOQ1 = new javax.swing.JPanel();
        btnCls = new javax.swing.JButton();
        jlCT = new javax.swing.JLabel();
        tfCT = new javax.swing.JTextField();
        jlN = new javax.swing.JLabel();
        tfPOQ = new javax.swing.JTextField();
        jlPR = new javax.swing.JLabel();
        tfPR = new javax.swing.JTextField();
        tfN = new javax.swing.JTextField();
        jlPOQ2 = new javax.swing.JLabel();
        jlB = new javax.swing.JLabel();
        tfB = new javax.swing.JTextField();
        jlN2 = new javax.swing.JLabel();
        tfSigmaL = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jlZ = new javax.swing.JLabel();
        tfZ = new javax.swing.JTextField();
        jlL = new javax.swing.JLabel();
        tfL = new javax.swing.JTextField();
        cbSelCPOQ = new javax.swing.JCheckBox();
        jlT = new javax.swing.JLabel();
        tfT = new javax.swing.JTextField();
        jlSigma = new javax.swing.JLabel();
        tfSigma = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlQ1 = new javax.swing.JLabel();
        tfQ1 = new javax.swing.JTextField();
        cbQ1 = new javax.swing.JCheckBox();
        jlD1 = new javax.swing.JLabel();
        tfD1 = new javax.swing.JTextField();
        cbD1 = new javax.swing.JComboBox<>();
        jlS1 = new javax.swing.JLabel();
        tfS1 = new javax.swing.JTextField();
        jlH1 = new javax.swing.JLabel();
        tfH1 = new javax.swing.JTextField();
        cbH1 = new javax.swing.JComboBox<>();
        jlN1 = new javax.swing.JLabel();
        tfN1 = new javax.swing.JTextField();
        cbN1 = new javax.swing.JComboBox<>();
        btnCalculate1 = new javax.swing.JButton();
        jpPOQ2 = new javax.swing.JPanel();
        btnCls1 = new javax.swing.JButton();
        jlCT1 = new javax.swing.JLabel();
        tfCT1 = new javax.swing.JTextField();
        jlPOQ1 = new javax.swing.JLabel();
        tfPOQ1 = new javax.swing.JTextField();
        jlPR1 = new javax.swing.JLabel();
        tfPR1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlSM = new javax.swing.JLabel();
        tfSM = new javax.swing.JTextField();
        jla = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        jlt = new javax.swing.JLabel();
        tft = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlQ3 = new javax.swing.JLabel();
        tfQ3 = new javax.swing.JTextField();
        cbQ3 = new javax.swing.JCheckBox();
        jlD3 = new javax.swing.JLabel();
        tfD3 = new javax.swing.JTextField();
        cbD3 = new javax.swing.JComboBox<>();
        jlS3 = new javax.swing.JLabel();
        tfS9 = new javax.swing.JTextField();
        jlH3 = new javax.swing.JLabel();
        tfH3 = new javax.swing.JTextField();
        cbH3 = new javax.swing.JComboBox<>();
        btnCalculate2 = new javax.swing.JButton();
        jpPOQ3 = new javax.swing.JPanel();
        btnCls2 = new javax.swing.JButton();
        jlCT2 = new javax.swing.JLabel();
        tfCT2 = new javax.swing.JTextField();
        jlPOQDes = new javax.swing.JLabel();
        tfPOQDes = new javax.swing.JTextField();
        jlqDes = new javax.swing.JLabel();
        tfqDes = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jlC1 = new javax.swing.JLabel();
        tfC1 = new javax.swing.JTextField();
        jlC2 = new javax.swing.JLabel();
        tfC2 = new javax.swing.JTextField();
        jlq = new javax.swing.JLabel();
        tfq = new javax.swing.JTextField();
        tfq1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQ.setText("Q :");

        tfQ.setEditable(false);
        tfQ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQActionPerformed(evt);
            }
        });

        cbQ.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQActionPerformed(evt);
            }
        });

        jlD.setText("D :");

        tfD.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDActionPerformed(evt);
            }
        });

        cbD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD.setPreferredSize(new java.awt.Dimension(70, 25));
        cbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDActionPerformed(evt);
            }
        });

        jlS.setText("S :");

        tfS.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSActionPerformed(evt);
            }
        });

        jlH.setText("H :");

        tfH.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHActionPerformed(evt);
            }
        });

        cbH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH.setPreferredSize(new java.awt.Dimension(70, 25));
        cbH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calcular");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnCls.setText("Limpiar");
        btnCls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClsActionPerformed(evt);
            }
        });

        jlCT.setText("Costo Total :");
        jlCT.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT.setEditable(false);
        tfCT.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCTActionPerformed(evt);
            }
        });

        jlN.setText("N :");
        jlN.setMaximumSize(new java.awt.Dimension(80, 16));
        jlN.setMinimumSize(new java.awt.Dimension(80, 16));
        jlN.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQ.setEditable(false);
        tfPOQ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQActionPerformed(evt);
            }
        });

        jlPR.setText("PR :");
        jlPR.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPR.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPR.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPR.setEditable(false);
        tfPR.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPRActionPerformed(evt);
            }
        });

        tfN.setEditable(false);
        tfN.setMinimumSize(new java.awt.Dimension(60, 20));
        tfN.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNActionPerformed(evt);
            }
        });

        jlPOQ2.setText("POQ :");
        jlPOQ2.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQ2.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQ2.setPreferredSize(new java.awt.Dimension(80, 16));

        jlB.setText("B :");
        jlB.setMaximumSize(new java.awt.Dimension(80, 16));
        jlB.setMinimumSize(new java.awt.Dimension(80, 16));
        jlB.setPreferredSize(new java.awt.Dimension(80, 16));

        tfB.setEditable(false);
        tfB.setMinimumSize(new java.awt.Dimension(60, 20));
        tfB.setPreferredSize(new java.awt.Dimension(70, 25));
        tfB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBActionPerformed(evt);
            }
        });

        jlN2.setText("σL :");
        jlN2.setMaximumSize(new java.awt.Dimension(80, 16));
        jlN2.setMinimumSize(new java.awt.Dimension(80, 16));
        jlN2.setPreferredSize(new java.awt.Dimension(80, 16));

        tfSigmaL.setEditable(false);
        tfSigmaL.setMinimumSize(new java.awt.Dimension(60, 20));
        tfSigmaL.setPreferredSize(new java.awt.Dimension(70, 25));
        tfSigmaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSigmaLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ1Layout = new javax.swing.GroupLayout(jpPOQ1);
        jpPOQ1.setLayout(jpPOQ1Layout);
        jpPOQ1Layout.setHorizontalGroup(
            jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPOQ1Layout.createSequentialGroup()
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPOQ1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlCT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlPOQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPOQ1Layout.createSequentialGroup()
                                .addComponent(jlN2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSigmaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpPOQ1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnCls)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpPOQ1Layout.setVerticalGroup(
            jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSigmaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnCls)
                .addGap(72, 72, 72))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlZ.setText("Z :");

        tfZ.setEditable(false);
        tfZ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZActionPerformed(evt);
            }
        });

        jlL.setText("L :");

        tfL.setPreferredSize(new java.awt.Dimension(70, 25));
        tfL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLActionPerformed(evt);
            }
        });

        cbSelCPOQ.setText("Demanda Variable");
        cbSelCPOQ.setPreferredSize(new java.awt.Dimension(25, 25));
        cbSelCPOQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelCPOQActionPerformed(evt);
            }
        });

        jlT.setText("t :");

        tfT.setEditable(false);
        tfT.setPreferredSize(new java.awt.Dimension(70, 25));
        tfT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTActionPerformed(evt);
            }
        });

        jlSigma.setText("σ :");

        tfSigma.setEditable(false);
        tfSigma.setPreferredSize(new java.awt.Dimension(70, 25));
        tfSigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSigmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPOQLayout = new javax.swing.GroupLayout(pPOQ);
        pPOQ.setLayout(pPOQLayout);
        pPOQLayout.setHorizontalGroup(
            pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPOQLayout.createSequentialGroup()
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pPOQLayout.createSequentialGroup()
                                        .addComponent(jlS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pPOQLayout.createSequentialGroup()
                                        .addComponent(jlD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnCalculate))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlZ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cbSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jlT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pPOQLayout.setVerticalGroup(
            pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPOQLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cbSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate)
                .addGap(29, 29, 29))
            .addComponent(jpPOQ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );

        mPanel.addTab("Compras (POQ)", pPOQ);

        jlQ1.setText("Q:");

        tfQ1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQ1ActionPerformed(evt);
            }
        });

        cbQ1.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQ1ActionPerformed(evt);
            }
        });

        jlD1.setText("D:");

        tfD1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfD1ActionPerformed(evt);
            }
        });

        cbD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD1.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS1.setText("S:");

        tfS1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfS1ActionPerformed(evt);
            }
        });

        jlH1.setText("H:");

        tfH1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfH1ActionPerformed(evt);
            }
        });

        cbH1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH1.setPreferredSize(new java.awt.Dimension(70, 25));

        jlN1.setText("N:");

        tfN1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfN1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN1ActionPerformed(evt);
            }
        });

        cbN1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbN1.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCalculate1.setText("Calcular");

        btnCls1.setText("Limpiar");

        jlCT1.setText("Costo Total:");
        jlCT1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT1ActionPerformed(evt);
            }
        });

        jlPOQ1.setText("POQ:");
        jlPOQ1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQ1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQ1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQ1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQ1ActionPerformed(evt);
            }
        });

        jlPR1.setText("PR:");
        jlPR1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPR1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPR1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPR1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ2Layout = new javax.swing.GroupLayout(jpPOQ2);
        jpPOQ2.setLayout(jpPOQ2Layout);
        jpPOQ2Layout.setHorizontalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls1)
                .addGap(59, 59, 59))
            .addGroup(jpPOQ2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addComponent(jlPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPOQ2Layout.createSequentialGroup()
                            .addComponent(jlPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPOQ2Layout.createSequentialGroup()
                            .addComponent(jlCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPOQ2Layout.setVerticalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls1)
                .addGap(37, 37, 37))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlSM.setText("SM:");

        tfSM.setPreferredSize(new java.awt.Dimension(70, 25));
        tfSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSMActionPerformed(evt);
            }
        });

        jla.setText("a:");

        tfa.setPreferredSize(new java.awt.Dimension(70, 25));
        tfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaActionPerformed(evt);
            }
        });

        jlt.setText("t:");

        tft.setPreferredSize(new java.awt.Dimension(70, 25));
        tft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlS1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlSM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(280, 280, 280)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlD1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlS1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlH1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate1)
                .addGap(50, 50, 50))
            .addComponent(jpPOQ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
        );

        mPanel.addTab("Produccion (***)", jPanel3);

        jlQ3.setText("Q:");

        tfQ3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQ3ActionPerformed(evt);
            }
        });

        cbQ3.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQ3ActionPerformed(evt);
            }
        });

        jlD3.setText("D:");

        tfD3.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfD3ActionPerformed(evt);
            }
        });

        cbD3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD3.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS3.setText("S:");

        tfS9.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfS9ActionPerformed(evt);
            }
        });

        jlH3.setText("H:");

        tfH3.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfH3ActionPerformed(evt);
            }
        });

        cbH3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH3.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCalculate2.setText("Calcular");

        btnCls2.setText("Limpiar");

        jlCT2.setText("Costo Total:");
        jlCT2.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT2.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT2.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT2ActionPerformed(evt);
            }
        });

        jlPOQDes.setText("POQ*:");
        jlPOQDes.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQDes.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQDes.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQDes.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQDesActionPerformed(evt);
            }
        });

        jlqDes.setText("q-:");
        jlqDes.setMaximumSize(new java.awt.Dimension(80, 16));
        jlqDes.setMinimumSize(new java.awt.Dimension(80, 16));
        jlqDes.setPreferredSize(new java.awt.Dimension(80, 16));

        tfqDes.setPreferredSize(new java.awt.Dimension(70, 25));
        tfqDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfqDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ3Layout = new javax.swing.GroupLayout(jpPOQ3);
        jpPOQ3.setLayout(jpPOQ3Layout);
        jpPOQ3Layout.setHorizontalGroup(
            jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls2)
                .addGap(59, 59, 59))
            .addGroup(jpPOQ3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPOQ3Layout.createSequentialGroup()
                        .addComponent(jlqDes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfqDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPOQ3Layout.createSequentialGroup()
                            .addComponent(jlPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPOQ3Layout.createSequentialGroup()
                            .addComponent(jlCT2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPOQ3Layout.setVerticalGroup(
            jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlqDes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfqDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls2)
                .addGap(37, 37, 37))
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlC1.setText("C1:");

        tfC1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC1ActionPerformed(evt);
            }
        });

        jlC2.setText("C2:");

        tfC2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC2ActionPerformed(evt);
            }
        });

        jlq.setText("q:");

        tfq.setPreferredSize(new java.awt.Dimension(70, 25));
        tfq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfqActionPerformed(evt);
            }
        });

        tfq1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfq1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlH3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlS3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlD3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlC2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(306, 306, 306)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlD3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlS3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlH3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnCalculate2)
                .addGap(50, 50, 50))
            .addComponent(jpPOQ3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
        );

        mPanel.addTab("Descuento. (EOQ)", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQActionPerformed

    private void Var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Var1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Var1ActionPerformed

    private void cbQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQActionPerformed

        if (!cbQ.isSelected()) {

            tfQ.setEditable(false);
            tfT.setEditable(false);

            tfD.setEditable(true);
            tfS.setEditable(true);
            tfH.setEditable(true);

        } else {

            tfQ.setEditable(true);

            if (cbSelCPOQ.isSelected()) {

                tfT.setEditable(true);
                tfD.setEditable(false);
                tfS.setEditable(false);
                tfH.setEditable(false);

            }

        }
    }//GEN-LAST:event_cbQActionPerformed

    private void tfDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDActionPerformed

    }//GEN-LAST:event_tfDActionPerformed

    private void tfSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSActionPerformed

    }//GEN-LAST:event_tfSActionPerformed

    private void tfHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHActionPerformed
    }//GEN-LAST:event_tfHActionPerformed

    private void tfNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNActionPerformed

    private void tfCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCTActionPerformed

    private void tfPOQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQActionPerformed

    private void tfQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQ1ActionPerformed

    private void cbQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQ1ActionPerformed

    private void tfD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfD1ActionPerformed

    private void tfS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfS1ActionPerformed

    private void tfH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfH1ActionPerformed

    private void tfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN1ActionPerformed

    private void tfCT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT1ActionPerformed

    private void tfPOQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQ1ActionPerformed

    private void tfZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZActionPerformed

    private void tfLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLActionPerformed

    private void tfSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSMActionPerformed

    private void tfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaActionPerformed

    private void tftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftActionPerformed

    private void cbSelCPOQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelCPOQActionPerformed

        if (cbSelCPOQ.isSelected()) {

            tfZ.setEditable(true);
            tfSigma.setEditable(true);

            if (cbQ.isSelected()) {

                tfT.setEditable(true);
                tfD.setEditable(false);
                tfD.setEditable(false);
                tfS.setEditable(false);
                tfH.setEditable(false);

            }

        } else {

            tfZ.setEditable(false);
            tfSigma.setEditable(false);
            tfT.setEditable(false);
            tfD.setEditable(true);
            tfS.setEditable(true);
            tfH.setEditable(true);

        }

    }//GEN-LAST:event_cbSelCPOQActionPerformed

    private void tfPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPRActionPerformed

    private void tfPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPR1ActionPerformed

    private void tfQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQ3ActionPerformed

    private void cbQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQ3ActionPerformed

    private void tfD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfD3ActionPerformed

    private void tfS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfS9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfS9ActionPerformed

    private void tfH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfH3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfH3ActionPerformed

    private void tfCT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT2ActionPerformed

    private void tfPOQDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQDesActionPerformed

    private void tfqDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfqDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfqDesActionPerformed

    private void tfC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC1ActionPerformed

    private void tfqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfqActionPerformed

    private void tfC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC2ActionPerformed

    private void btnClsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClsActionPerformed
        // limpieza de todos los textfields

        tfQ.setText("");
        tfD.setText("");
        tfS.setText("");
        tfH.setText("");
        tfL.setText("");
        tfZ.setText("");
        tfSigma.setText("");
        tfT.setText("");
        tfPOQ.setText("");
        tfPR.setText("");
        tfCT.setText("");
        tfB.setText("");
        tfN.setText("");
        tfSigmaL.setText("");
        cbSelCPOQ.setSelected(false);
        cbQ.setSelected(false);
        



    }//GEN-LAST:event_btnClsActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        EOQ eoq;
        DecimalFormat decimalFormat = new DecimalFormat("#.##");

        // Validacion para EOQ simple
        if (!cbSelCPOQ.isSelected()) {

            if (tfD.getText().isEmpty() || tfS.getText().isEmpty() || tfH.getText().isEmpty()
                    || tfL.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
                return;
            }

            if (cbQ.isSelected()) {
                if (tfQ.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
                    return;
                }
            }
        }

        // Validacion para EOQ con CPOQ
        if (cbSelCPOQ.isSelected()) {

            if (tfQ.getText().isEmpty() || tfL.getText().isEmpty() || tfZ.getText().isEmpty()
                    || tfSigma.getText().isEmpty()
                    || tfT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
                return;
            }

            if (!cbQ.isSelected()) {

                if (tfD.getText().isEmpty() || tfS.getText().isEmpty() || tfH.getText().isEmpty()
                        || tfL.getText().isEmpty() || tfZ.getText().isEmpty() || tfSigma.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
                    return;

                }
            }

        }

        if (!cbSelCPOQ.isSelected()) {

            dTx = Double.parseDouble(tfD.getText());
            sTx = Double.parseDouble(tfS.getText());
            hTx = Double.parseDouble(tfH.getText());
            lTx = Double.parseDouble(tfL.getText());

            // qTx = Double.parseDouble(tfQ.getText());
            // zTx = Double.parseDouble(tfZ.getText());
            // sigTx = Double.parseDouble(tfSigma.getText());
            // tTx = Double.parseDouble(tfT.getText());
            eoq = new EOQ(dTx, tD, sTx, hTx, tH, lTx);

            tfPOQ.setText(decimalFormat.format(eoq.Q));
            tfCT.setText(decimalFormat.format(eoq.C));
            tfN.setText(decimalFormat.format(eoq.N));
            tfPR.setText(decimalFormat.format(eoq.R));
            System.err.println("NO Variable");

        } else {

            //    dTx = Double.parseDouble(tfD.getText());
            //    sTx = Double.parseDouble(tfS.getText());
            //    hTx = Double.parseDouble(tfH.getText());
            lTx = Double.parseDouble(tfL.getText());

            qTx = Double.parseDouble(tfQ.getText());
            zTx = Double.parseDouble(tfZ.getText());
            sigTx = Double.parseDouble(tfSigma.getText());
            tTx = Double.parseDouble(tfT.getText());

            eoq = new EOQ(qTx, lTx, zTx, sigTx, tTx);

            tfSigmaL.setText(decimalFormat.format(eoq.SigmaL));
            tfB.setText(decimalFormat.format(eoq.B));
            tfPR.setText(decimalFormat.format(eoq.R));
            tfQ.setText(decimalFormat.format(eoq.Q));

            System.err.println("Variable");
        }

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void cbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDActionPerformed

        switch (cbD.getSelectedIndex()) {
            case 0:
                tD = 1;
                break;

            case 4:
                tD = 2;
                break;

        }

        System.out.println("td: " + tD);

    }//GEN-LAST:event_cbDActionPerformed

    private void cbHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHActionPerformed
        switch (cbH.getSelectedIndex()) {
            case 0:
                tH = 1;
                break;

            case 4:
                tH = 2;
                break;
            default:
                tD = 1;
        }

        System.out.println("tH: " + tH);
    }//GEN-LAST:event_cbHActionPerformed

    private void tfTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTActionPerformed

    private void tfBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBActionPerformed

    private void tfSigmaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSigmaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSigmaLActionPerformed

    private void tfSigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSigmaActionPerformed

    private void tfq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfq1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate1;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnCls;
    private javax.swing.JButton btnCls1;
    private javax.swing.JButton btnCls2;
    private javax.swing.JComboBox<String> cbD;
    private javax.swing.JComboBox<String> cbD1;
    private javax.swing.JComboBox<String> cbD3;
    private javax.swing.JComboBox<String> cbH;
    private javax.swing.JComboBox<String> cbH1;
    private javax.swing.JComboBox<String> cbH3;
    private javax.swing.JComboBox<String> cbN1;
    private javax.swing.JCheckBox cbQ;
    private javax.swing.JCheckBox cbQ1;
    private javax.swing.JCheckBox cbQ3;
    private javax.swing.JCheckBox cbSelCPOQ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlB;
    private javax.swing.JLabel jlC1;
    private javax.swing.JLabel jlC2;
    private javax.swing.JLabel jlCT;
    private javax.swing.JLabel jlCT1;
    private javax.swing.JLabel jlCT2;
    private javax.swing.JLabel jlD;
    private javax.swing.JLabel jlD1;
    private javax.swing.JLabel jlD3;
    private javax.swing.JLabel jlH;
    private javax.swing.JLabel jlH1;
    private javax.swing.JLabel jlH3;
    private javax.swing.JLabel jlL;
    private javax.swing.JLabel jlN;
    private javax.swing.JLabel jlN1;
    private javax.swing.JLabel jlN2;
    private javax.swing.JLabel jlPOQ1;
    private javax.swing.JLabel jlPOQ2;
    private javax.swing.JLabel jlPOQDes;
    private javax.swing.JLabel jlPR;
    private javax.swing.JLabel jlPR1;
    private javax.swing.JLabel jlQ;
    private javax.swing.JLabel jlQ1;
    private javax.swing.JLabel jlQ3;
    private javax.swing.JLabel jlS;
    private javax.swing.JLabel jlS1;
    private javax.swing.JLabel jlS3;
    private javax.swing.JLabel jlSM;
    private javax.swing.JLabel jlSigma;
    private javax.swing.JLabel jlT;
    private javax.swing.JLabel jlZ;
    private javax.swing.JLabel jla;
    private javax.swing.JLabel jlq;
    private javax.swing.JLabel jlqDes;
    private javax.swing.JLabel jlt;
    private javax.swing.JPanel jpPOQ1;
    private javax.swing.JPanel jpPOQ2;
    private javax.swing.JPanel jpPOQ3;
    private javax.swing.JTabbedPane mPanel;
    private javax.swing.JPanel pPOQ;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfC1;
    private javax.swing.JTextField tfC2;
    private javax.swing.JTextField tfCT;
    private javax.swing.JTextField tfCT1;
    private javax.swing.JTextField tfCT2;
    private javax.swing.JTextField tfD;
    private javax.swing.JTextField tfD1;
    private javax.swing.JTextField tfD3;
    private javax.swing.JTextField tfH;
    private javax.swing.JTextField tfH1;
    private javax.swing.JTextField tfH3;
    private javax.swing.JTextField tfL;
    private javax.swing.JTextField tfN;
    private javax.swing.JTextField tfN1;
    private javax.swing.JTextField tfPOQ;
    private javax.swing.JTextField tfPOQ1;
    private javax.swing.JTextField tfPOQDes;
    private javax.swing.JTextField tfPR;
    private javax.swing.JTextField tfPR1;
    private javax.swing.JTextField tfQ;
    private javax.swing.JTextField tfQ1;
    private javax.swing.JTextField tfQ3;
    private javax.swing.JTextField tfS;
    private javax.swing.JTextField tfS1;
    private javax.swing.JTextField tfS9;
    private javax.swing.JTextField tfSM;
    private javax.swing.JTextField tfSigma;
    private javax.swing.JTextField tfSigmaL;
    private javax.swing.JTextField tfT;
    private javax.swing.JTextField tfZ;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tfq;
    private javax.swing.JTextField tfq1;
    private javax.swing.JTextField tfqDes;
    private javax.swing.JTextField tft;
    // End of variables declaration//GEN-END:variables
}
