package com.onnx.lirufiru.app.components;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanel = new javax.swing.JTabbedPane();
        pPOQ = new javax.swing.JPanel();
        jlQ = new javax.swing.JLabel();
        tfQ = new javax.swing.JTextField();
        cbQ = new javax.swing.JCheckBox();
        jlD = new javax.swing.JLabel();
        tfD = new javax.swing.JTextField();
        cbD = new javax.swing.JComboBox<>();
        jlS = new javax.swing.JLabel();
        tfS = new javax.swing.JTextField();
        jlH = new javax.swing.JLabel();
        tfH = new javax.swing.JTextField();
        cbH = new javax.swing.JComboBox<>();
        jlN = new javax.swing.JLabel();
        tfN = new javax.swing.JTextField();
        cbN = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        jpPOQ1 = new javax.swing.JPanel();
        btnCls = new javax.swing.JButton();
        jlCT = new javax.swing.JLabel();
        tfCT = new javax.swing.JTextField();
        jlPOQ = new javax.swing.JLabel();
        tfPOQ = new javax.swing.JTextField();
        jlPR = new javax.swing.JLabel();
        tfPR = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jlQ2 = new javax.swing.JLabel();
        tfQ2 = new javax.swing.JTextField();
        cbQ2 = new javax.swing.JCheckBox();
        jlD2 = new javax.swing.JLabel();
        tfD2 = new javax.swing.JTextField();
        cbD2 = new javax.swing.JComboBox<>();
        jlS2 = new javax.swing.JLabel();
        tfS2 = new javax.swing.JTextField();
        jlH2 = new javax.swing.JLabel();
        tfH2 = new javax.swing.JTextField();
        cbH2 = new javax.swing.JComboBox<>();
        jlN2 = new javax.swing.JLabel();
        tfN2 = new javax.swing.JTextField();
        cbN2 = new javax.swing.JComboBox<>();
        jlSigma = new javax.swing.JLabel();
        tfSigma = new javax.swing.JTextField();
        jlZ = new javax.swing.JLabel();
        tfZ = new javax.swing.JTextField();
        jlL = new javax.swing.JLabel();
        tfL = new javax.swing.JTextField();
        tfSelSigma = new javax.swing.JTextField();
        cbSelSigma = new javax.swing.JCheckBox();
        tfSelCPOQ = new javax.swing.JTextField();
        cbSelCPOQ = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jlQ1 = new javax.swing.JLabel();
        tfQ1 = new javax.swing.JTextField();
        cbQ1 = new javax.swing.JCheckBox();
        jlD1 = new javax.swing.JLabel();
        tfD1 = new javax.swing.JTextField();
        cbD1 = new javax.swing.JComboBox<>();
        jlS1 = new javax.swing.JLabel();
        tfS1 = new javax.swing.JTextField();
        jlH1 = new javax.swing.JLabel();
        tfH1 = new javax.swing.JTextField();
        cbH1 = new javax.swing.JComboBox<>();
        jlN1 = new javax.swing.JLabel();
        tfN1 = new javax.swing.JTextField();
        cbN1 = new javax.swing.JComboBox<>();
        btnCalculate1 = new javax.swing.JButton();
        jpPOQ2 = new javax.swing.JPanel();
        btnCls1 = new javax.swing.JButton();
        jlCT1 = new javax.swing.JLabel();
        tfCT1 = new javax.swing.JTextField();
        jlPOQ1 = new javax.swing.JLabel();
        tfPOQ1 = new javax.swing.JTextField();
        jlPR1 = new javax.swing.JLabel();
        tfPR1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlSM = new javax.swing.JLabel();
        tfSM = new javax.swing.JTextField();
        jla = new javax.swing.JLabel();
        tfa = new javax.swing.JTextField();
        jlt = new javax.swing.JLabel();
        tft = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlQ3 = new javax.swing.JLabel();
        tfQ3 = new javax.swing.JTextField();
        cbQ3 = new javax.swing.JCheckBox();
        jlD3 = new javax.swing.JLabel();
        tfD3 = new javax.swing.JTextField();
        cbD3 = new javax.swing.JComboBox<>();
        jlS3 = new javax.swing.JLabel();
        tfS9 = new javax.swing.JTextField();
        jlH3 = new javax.swing.JLabel();
        tfH3 = new javax.swing.JTextField();
        cbH3 = new javax.swing.JComboBox<>();
        btnCalculate2 = new javax.swing.JButton();
        jpPOQ3 = new javax.swing.JPanel();
        btnCls2 = new javax.swing.JButton();
        jlCT2 = new javax.swing.JLabel();
        tfCT2 = new javax.swing.JTextField();
        jlPOQDes = new javax.swing.JLabel();
        tfPOQDes = new javax.swing.JTextField();
        jlqDes = new javax.swing.JLabel();
        tfqDes = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jlC1 = new javax.swing.JLabel();
        tfC1 = new javax.swing.JTextField();
        jlC2 = new javax.swing.JLabel();
        tfC2 = new javax.swing.JTextField();
        jlq = new javax.swing.JLabel();
        tfq = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlQ.setText("Q:");

        tfQ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQActionPerformed(evt);
            }
        });

        cbQ.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQActionPerformed(evt);
            }
        });

        jlD.setText("D:");

        tfD.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDActionPerformed(evt);
            }
        });

        cbD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS.setText("S:");

        tfS.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSActionPerformed(evt);
            }
        });

        jlH.setText("H:");

        tfH.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHActionPerformed(evt);
            }
        });

        cbH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH.setPreferredSize(new java.awt.Dimension(70, 25));

        jlN.setText("N:");

        tfN.setMinimumSize(new java.awt.Dimension(60, 20));
        tfN.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNActionPerformed(evt);
            }
        });

        cbN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbN.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCalculate.setText("Calcular");

        btnCls.setText("Limpiar");

        jlCT.setText("Costo Total:");
        jlCT.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCTActionPerformed(evt);
            }
        });

        jlPOQ.setText("POQ:");
        jlPOQ.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQ.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQ.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQActionPerformed(evt);
            }
        });

        jlPR.setText("PR:");
        jlPR.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPR.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPR.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPR.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ1Layout = new javax.swing.GroupLayout(jpPOQ1);
        jpPOQ1.setLayout(jpPOQ1Layout);
        jpPOQ1Layout.setHorizontalGroup(
            jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls)
                .addGap(59, 59, 59))
            .addGroup(jpPOQ1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPOQ1Layout.createSequentialGroup()
                        .addComponent(jlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPOQ1Layout.createSequentialGroup()
                            .addComponent(jlPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPOQ1Layout.createSequentialGroup()
                            .addComponent(jlCT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPOQ1Layout.setVerticalGroup(
            jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls)
                .addGap(37, 37, 37))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlQ2.setText("Q:");

        tfQ2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQ2ActionPerformed(evt);
            }
        });

        cbQ2.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQ2ActionPerformed(evt);
            }
        });

        jlD2.setText("D:");

        tfD2.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfD2ActionPerformed(evt);
            }
        });

        cbD2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD2.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS2.setText("S:");

        tfS2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfS2ActionPerformed(evt);
            }
        });

        jlH2.setText("H:");

        tfH2.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfH2ActionPerformed(evt);
            }
        });

        cbH2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH2.setPreferredSize(new java.awt.Dimension(70, 25));

        jlN2.setText("N:");

        tfN2.setMinimumSize(new java.awt.Dimension(60, 20));
        tfN2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN2ActionPerformed(evt);
            }
        });

        cbN2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbN2.setPreferredSize(new java.awt.Dimension(70, 25));

        jlSigma.setText("Sigma:");

        tfSigma.setPreferredSize(new java.awt.Dimension(70, 25));
        tfSigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSigmaActionPerformed(evt);
            }
        });

        jlZ.setText("Z:");

        tfZ.setPreferredSize(new java.awt.Dimension(70, 25));
        tfZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZActionPerformed(evt);
            }
        });

        jlL.setText("L:");

        tfL.setPreferredSize(new java.awt.Dimension(70, 25));
        tfL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLActionPerformed(evt);
            }
        });

        tfSelSigma.setText("Selecciona POQ Sigma");
        tfSelSigma.setPreferredSize(new java.awt.Dimension(70, 25));

        cbSelSigma.setPreferredSize(new java.awt.Dimension(25, 25));
        cbSelSigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelSigmaActionPerformed(evt);
            }
        });

        tfSelCPOQ.setText("Selecciona POQ normal");
        tfSelCPOQ.setPreferredSize(new java.awt.Dimension(70, 25));

        cbSelCPOQ.setPreferredSize(new java.awt.Dimension(25, 25));
        cbSelCPOQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelCPOQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPOQLayout = new javax.swing.GroupLayout(pPOQ);
        pPOQ.setLayout(pPOQLayout);
        pPOQLayout.setHorizontalGroup(
            pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPOQLayout.createSequentialGroup()
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pPOQLayout.createSequentialGroup()
                                    .addComponent(jlH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pPOQLayout.createSequentialGroup()
                                    .addComponent(jlQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pPOQLayout.createSequentialGroup()
                                    .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pPOQLayout.createSequentialGroup()
                                            .addComponent(jlS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pPOQLayout.createSequentialGroup()
                                            .addComponent(jlD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pPOQLayout.createSequentialGroup()
                                    .addComponent(jlN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCalculate))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(cbSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlZ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlH2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pPOQLayout.createSequentialGroup()
                                        .addComponent(jlS2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pPOQLayout.createSequentialGroup()
                                        .addComponent(jlD2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlN2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(jlSigma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pPOQLayout.createSequentialGroup()
                                .addComponent(cbSelSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfSelSigma, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                .addGap(102, 102, 102)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pPOQLayout.setVerticalGroup(
            pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPOQLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfSelSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSelSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSelCPOQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlQ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlD2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlS2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlH2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlN2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnCalculate))
                    .addGroup(pPOQLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pPOQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(jpPOQ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );

        mPanel.addTab("Compras (POQ)", pPOQ);

        jlQ1.setText("Q:");

        tfQ1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQ1ActionPerformed(evt);
            }
        });

        cbQ1.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQ1ActionPerformed(evt);
            }
        });

        jlD1.setText("D:");

        tfD1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfD1ActionPerformed(evt);
            }
        });

        cbD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD1.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS1.setText("S:");

        tfS1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfS1ActionPerformed(evt);
            }
        });

        jlH1.setText("H:");

        tfH1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfH1ActionPerformed(evt);
            }
        });

        cbH1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH1.setPreferredSize(new java.awt.Dimension(70, 25));

        jlN1.setText("N:");

        tfN1.setMinimumSize(new java.awt.Dimension(60, 20));
        tfN1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN1ActionPerformed(evt);
            }
        });

        cbN1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbN1.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCalculate1.setText("Calcular");

        btnCls1.setText("Limpiar");

        jlCT1.setText("Costo Total:");
        jlCT1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT1ActionPerformed(evt);
            }
        });

        jlPOQ1.setText("POQ:");
        jlPOQ1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQ1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQ1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQ1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQ1ActionPerformed(evt);
            }
        });

        jlPR1.setText("PR:");
        jlPR1.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPR1.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPR1.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPR1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ2Layout = new javax.swing.GroupLayout(jpPOQ2);
        jpPOQ2.setLayout(jpPOQ2Layout);
        jpPOQ2Layout.setHorizontalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls1)
                .addGap(59, 59, 59))
            .addGroup(jpPOQ2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addComponent(jlPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPOQ2Layout.createSequentialGroup()
                            .addComponent(jlPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPOQ2Layout.createSequentialGroup()
                            .addComponent(jlCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPOQ2Layout.setVerticalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPR1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls1)
                .addGap(37, 37, 37))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlSM.setText("SM:");

        tfSM.setPreferredSize(new java.awt.Dimension(70, 25));
        tfSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSMActionPerformed(evt);
            }
        });

        jla.setText("a:");

        tfa.setPreferredSize(new java.awt.Dimension(70, 25));
        tfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfaActionPerformed(evt);
            }
        });

        jlt.setText("t:");

        tft.setPreferredSize(new java.awt.Dimension(70, 25));
        tft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlS1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlD1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlSM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(432, 432, 432)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlD1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlS1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlH1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnCalculate1)
                .addGap(50, 50, 50))
            .addComponent(jpPOQ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
        );

        mPanel.addTab("Produccion (***)", jPanel3);

        jlQ3.setText("Q:");

        tfQ3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQ3ActionPerformed(evt);
            }
        });

        cbQ3.setPreferredSize(new java.awt.Dimension(25, 25));
        cbQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQ3ActionPerformed(evt);
            }
        });

        jlD3.setText("D:");

        tfD3.setMinimumSize(new java.awt.Dimension(60, 20));
        tfD3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfD3ActionPerformed(evt);
            }
        });

        cbD3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbD3.setPreferredSize(new java.awt.Dimension(70, 25));

        jlS3.setText("S:");

        tfS9.setPreferredSize(new java.awt.Dimension(70, 25));
        tfS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfS9ActionPerformed(evt);
            }
        });

        jlH3.setText("H:");

        tfH3.setMinimumSize(new java.awt.Dimension(60, 20));
        tfH3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfH3ActionPerformed(evt);
            }
        });

        cbH3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Quincena", "Mes", "Año" }));
        cbH3.setPreferredSize(new java.awt.Dimension(70, 25));

        btnCalculate2.setText("Calcular");

        btnCls2.setText("Limpiar");

        jlCT2.setText("Costo Total:");
        jlCT2.setMaximumSize(new java.awt.Dimension(80, 16));
        jlCT2.setMinimumSize(new java.awt.Dimension(80, 16));
        jlCT2.setPreferredSize(new java.awt.Dimension(80, 16));

        tfCT2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT2ActionPerformed(evt);
            }
        });

        jlPOQDes.setText("POQ*:");
        jlPOQDes.setMaximumSize(new java.awt.Dimension(80, 16));
        jlPOQDes.setMinimumSize(new java.awt.Dimension(80, 16));
        jlPOQDes.setPreferredSize(new java.awt.Dimension(80, 16));

        tfPOQDes.setPreferredSize(new java.awt.Dimension(70, 25));
        tfPOQDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPOQDesActionPerformed(evt);
            }
        });

        jlqDes.setText("q-:");
        jlqDes.setMaximumSize(new java.awt.Dimension(80, 16));
        jlqDes.setMinimumSize(new java.awt.Dimension(80, 16));
        jlqDes.setPreferredSize(new java.awt.Dimension(80, 16));

        tfqDes.setPreferredSize(new java.awt.Dimension(70, 25));
        tfqDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfqDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPOQ3Layout = new javax.swing.GroupLayout(jpPOQ3);
        jpPOQ3.setLayout(jpPOQ3Layout);
        jpPOQ3Layout.setHorizontalGroup(
            jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls2)
                .addGap(59, 59, 59))
            .addGroup(jpPOQ3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpPOQ3Layout.createSequentialGroup()
                        .addComponent(jlqDes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfqDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPOQ3Layout.createSequentialGroup()
                            .addComponent(jlPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpPOQ3Layout.createSequentialGroup()
                            .addComponent(jlCT2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPOQ3Layout.setVerticalGroup(
            jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPOQDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlqDes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfqDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCls2)
                .addGap(37, 37, 37))
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlC1.setText("C1:");

        tfC1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC1ActionPerformed(evt);
            }
        });

        jlC2.setText("C2:");

        tfC2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC2ActionPerformed(evt);
            }
        });

        jlq.setText("q:");

        tfq.setPreferredSize(new java.awt.Dimension(70, 25));
        tfq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlH3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlS3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlD3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlC2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(432, 432, 432)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlD3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlS3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlH3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnCalculate2)
                .addGap(50, 50, 50))
            .addComponent(jpPOQ3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
        );

        mPanel.addTab("Descuento. (EOQ)", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQActionPerformed

    private void Var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Var1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Var1ActionPerformed

    private void cbQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQActionPerformed

    private void tfDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDActionPerformed

    private void tfSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSActionPerformed

    private void tfHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHActionPerformed

    private void tfNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNActionPerformed

    private void tfCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCTActionPerformed

    private void tfPOQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQActionPerformed

    private void tfQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQ1ActionPerformed

    private void cbQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQ1ActionPerformed

    private void tfD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfD1ActionPerformed

    private void tfS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfS1ActionPerformed

    private void tfH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfH1ActionPerformed

    private void tfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN1ActionPerformed

    private void tfCT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT1ActionPerformed

    private void tfPOQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQ1ActionPerformed

    private void tfQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQ2ActionPerformed

    private void cbQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQ2ActionPerformed

    private void tfD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfD2ActionPerformed

    private void tfS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfS2ActionPerformed

    private void tfH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfH2ActionPerformed

    private void tfN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN2ActionPerformed

    private void tfSigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSigmaActionPerformed

    private void tfZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZActionPerformed

    private void tfLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLActionPerformed

    private void tfSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSMActionPerformed

    private void tfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfaActionPerformed

    private void tftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftActionPerformed

    private void cbSelSigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelSigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelSigmaActionPerformed

    private void cbSelCPOQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelCPOQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelCPOQActionPerformed

    private void tfPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPRActionPerformed

    private void tfPR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPR1ActionPerformed

    private void tfQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQ3ActionPerformed

    private void cbQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQ3ActionPerformed

    private void tfD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfD3ActionPerformed

    private void tfS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfS9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfS9ActionPerformed

    private void tfH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfH3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfH3ActionPerformed

    private void tfCT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT2ActionPerformed

    private void tfPOQDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPOQDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPOQDesActionPerformed

    private void tfqDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfqDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfqDesActionPerformed

    private void tfC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC1ActionPerformed

    private void tfqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfqActionPerformed

    private void tfC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC2ActionPerformed

    // /**
    //  * @param args the command line arguments
    //  */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     //</editor-fold>
    //     //</editor-fold>
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new GUI().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate1;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnCls;
    private javax.swing.JButton btnCls1;
    private javax.swing.JButton btnCls2;
    private javax.swing.JComboBox<String> cbD;
    private javax.swing.JComboBox<String> cbD1;
    private javax.swing.JComboBox<String> cbD2;
    private javax.swing.JComboBox<String> cbD3;
    private javax.swing.JComboBox<String> cbH;
    private javax.swing.JComboBox<String> cbH1;
    private javax.swing.JComboBox<String> cbH2;
    private javax.swing.JComboBox<String> cbH3;
    private javax.swing.JComboBox<String> cbN;
    private javax.swing.JComboBox<String> cbN1;
    private javax.swing.JComboBox<String> cbN2;
    private javax.swing.JCheckBox cbQ;
    private javax.swing.JCheckBox cbQ1;
    private javax.swing.JCheckBox cbQ2;
    private javax.swing.JCheckBox cbQ3;
    private javax.swing.JCheckBox cbSelCPOQ;
    private javax.swing.JCheckBox cbSelSigma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlC1;
    private javax.swing.JLabel jlC2;
    private javax.swing.JLabel jlCT;
    private javax.swing.JLabel jlCT1;
    private javax.swing.JLabel jlCT2;
    private javax.swing.JLabel jlD;
    private javax.swing.JLabel jlD1;
    private javax.swing.JLabel jlD2;
    private javax.swing.JLabel jlD3;
    private javax.swing.JLabel jlH;
    private javax.swing.JLabel jlH1;
    private javax.swing.JLabel jlH2;
    private javax.swing.JLabel jlH3;
    private javax.swing.JLabel jlL;
    private javax.swing.JLabel jlN;
    private javax.swing.JLabel jlN1;
    private javax.swing.JLabel jlN2;
    private javax.swing.JLabel jlPOQ;
    private javax.swing.JLabel jlPOQ1;
    private javax.swing.JLabel jlPOQDes;
    private javax.swing.JLabel jlPR;
    private javax.swing.JLabel jlPR1;
    private javax.swing.JLabel jlQ;
    private javax.swing.JLabel jlQ1;
    private javax.swing.JLabel jlQ2;
    private javax.swing.JLabel jlQ3;
    private javax.swing.JLabel jlS;
    private javax.swing.JLabel jlS1;
    private javax.swing.JLabel jlS2;
    private javax.swing.JLabel jlS3;
    private javax.swing.JLabel jlSM;
    private javax.swing.JLabel jlSigma;
    private javax.swing.JLabel jlZ;
    private javax.swing.JLabel jla;
    private javax.swing.JLabel jlq;
    private javax.swing.JLabel jlqDes;
    private javax.swing.JLabel jlt;
    private javax.swing.JPanel jpPOQ1;
    private javax.swing.JPanel jpPOQ2;
    private javax.swing.JPanel jpPOQ3;
    private javax.swing.JTabbedPane mPanel;
    private javax.swing.JPanel pPOQ;
    private javax.swing.JTextField tfC1;
    private javax.swing.JTextField tfC2;
    private javax.swing.JTextField tfCT;
    private javax.swing.JTextField tfCT1;
    private javax.swing.JTextField tfCT2;
    private javax.swing.JTextField tfD;
    private javax.swing.JTextField tfD1;
    private javax.swing.JTextField tfD2;
    private javax.swing.JTextField tfD3;
    private javax.swing.JTextField tfH;
    private javax.swing.JTextField tfH1;
    private javax.swing.JTextField tfH2;
    private javax.swing.JTextField tfH3;
    private javax.swing.JTextField tfL;
    private javax.swing.JTextField tfN;
    private javax.swing.JTextField tfN1;
    private javax.swing.JTextField tfN2;
    private javax.swing.JTextField tfPOQ;
    private javax.swing.JTextField tfPOQ1;
    private javax.swing.JTextField tfPOQDes;
    private javax.swing.JTextField tfPR;
    private javax.swing.JTextField tfPR1;
    private javax.swing.JTextField tfQ;
    private javax.swing.JTextField tfQ1;
    private javax.swing.JTextField tfQ2;
    private javax.swing.JTextField tfQ3;
    private javax.swing.JTextField tfS;
    private javax.swing.JTextField tfS1;
    private javax.swing.JTextField tfS2;
    private javax.swing.JTextField tfS9;
    private javax.swing.JTextField tfSM;
    private javax.swing.JTextField tfSelCPOQ;
    private javax.swing.JTextField tfSelSigma;
    private javax.swing.JTextField tfSigma;
    private javax.swing.JTextField tfZ;
    private javax.swing.JTextField tfa;
    private javax.swing.JTextField tfq;
    private javax.swing.JTextField tfqDes;
    private javax.swing.JTextField tft;
    // End of variables declaration//GEN-END:variables
}
