package com.onnx.lirufiru.app.components;

import java.text.DecimalFormat;

public class Servidores extends javax.swing.JFrame {

    DecimalFormat dF = new DecimalFormat("#.####");
    double dTx = 0.0, sTx = 0.0, hTx = 0.0, lTx = 0.0, zTx = 0.0, sigTx = 0.0, qTx = 0.0, tTx = 0.0, aTx = 0.0;
    int tD = 1, tH = 1;

    /**
     * Creates new form GUI
     */
    public Servidores() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanel = new javax.swing.JTabbedPane();
        pUnServidor = new javax.swing.JPanel();
        jpPOQ2 = new javax.swing.JPanel();
        btnCls1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        L_UnServidor = new javax.swing.JTextField();
        jlLq1 = new javax.swing.JLabel();
        Lq_UnServidor = new javax.swing.JTextField();
        jlW1 = new javax.swing.JLabel();
        W_UnServidor = new javax.swing.JTextField();
        jlWq1 = new javax.swing.JLabel();
        Wq_UnServidor = new javax.swing.JTextField();
        jlCT1 = new javax.swing.JLabel();
        jlP01 = new javax.swing.JLabel();
        costoTotal_UnServidor = new javax.swing.JTextField();
        p0_UnServidor = new javax.swing.JTextField();
        jlL1 = new javax.swing.JLabel();
        jlRho1 = new javax.swing.JLabel();
        rho_UnServidor = new javax.swing.JTextField();
        costoTotalUnitario_UnServidor = new javax.swing.JTextField();
        jlCT2 = new javax.swing.JLabel();
        calcularUnServidor = new javax.swing.JButton();
        jllam1 = new javax.swing.JLabel();
        tflam1 = new javax.swing.JTextField();
        jlmu1 = new javax.swing.JLabel();
        tfmu1 = new javax.swing.JTextField();
        jlC_W1 = new javax.swing.JLabel();
        tfC_W1 = new javax.swing.JTextField();
        jlC_S1 = new javax.swing.JLabel();
        tfC_S1 = new javax.swing.JTextField();
        pMultiplesServidores = new javax.swing.JPanel();
        btnCalculate4 = new javax.swing.JButton();
        jllam2 = new javax.swing.JLabel();
        tflam2 = new javax.swing.JTextField();
        jlmu2 = new javax.swing.JLabel();
        tfmu2 = new javax.swing.JTextField();
        jpPOQ5 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        tfL2 = new javax.swing.JTextField();
        jlLq2 = new javax.swing.JLabel();
        tfLq2 = new javax.swing.JTextField();
        jlW2 = new javax.swing.JLabel();
        tfW2 = new javax.swing.JTextField();
        jlWq2 = new javax.swing.JLabel();
        tfWq2 = new javax.swing.JTextField();
        jlCT4 = new javax.swing.JLabel();
        jlP2 = new javax.swing.JLabel();
        tfCT4 = new javax.swing.JTextField();
        tfP2 = new javax.swing.JTextField();
        jlL2 = new javax.swing.JLabel();
        jlRho2 = new javax.swing.JLabel();
        tfRho2 = new javax.swing.JTextField();
        tfCET1 = new javax.swing.JTextField();
        jlCET1 = new javax.swing.JLabel();
        tfCST1 = new javax.swing.JTextField();
        jlCST1 = new javax.swing.JLabel();
        jlC_W2 = new javax.swing.JLabel();
        tfC_W2 = new javax.swing.JTextField();
        jlC_S2 = new javax.swing.JLabel();
        tfC_S2 = new javax.swing.JTextField();
        jls = new javax.swing.JLabel();
        tfls1 = new javax.swing.JTextField();
        btnCls4 = new javax.swing.JButton();
        pFuenteFinita = new javax.swing.JPanel();
        tfN1 = new javax.swing.JTextField();
        btnCalculate5 = new javax.swing.JButton();
        jllam3 = new javax.swing.JLabel();
        tflam3 = new javax.swing.JTextField();
        jlmu3 = new javax.swing.JLabel();
        tfmu3 = new javax.swing.JTextField();
        jlC_W3 = new javax.swing.JLabel();
        jpPOQ6 = new javax.swing.JPanel();
        btnCls5 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        tfL3 = new javax.swing.JTextField();
        jlLq3 = new javax.swing.JLabel();
        tfLq3 = new javax.swing.JTextField();
        jlW3 = new javax.swing.JLabel();
        tfW3 = new javax.swing.JTextField();
        jlWq3 = new javax.swing.JLabel();
        tfWq3 = new javax.swing.JTextField();
        jlCT5 = new javax.swing.JLabel();
        jlP3 = new javax.swing.JLabel();
        tfCT5 = new javax.swing.JTextField();
        tfP3 = new javax.swing.JTextField();
        jlL3 = new javax.swing.JLabel();
        jlRho3 = new javax.swing.JLabel();
        tfRho3 = new javax.swing.JTextField();
        tfCET2 = new javax.swing.JTextField();
        jlCET2 = new javax.swing.JLabel();
        tfCST2 = new javax.swing.JTextField();
        jlCST2 = new javax.swing.JLabel();
        tfC_W3 = new javax.swing.JTextField();
        jlC_S3 = new javax.swing.JLabel();
        tfC_S3 = new javax.swing.JTextField();
        jlN1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCls1.setText("Limpiar");
        btnCls1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCls1ActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        L_UnServidor.setEditable(false);
        L_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        L_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_UnServidorActionPerformed(evt);
            }
        });

        jlLq1.setText("Lq:");

        Lq_UnServidor.setEditable(false);
        Lq_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        Lq_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lq_UnServidorActionPerformed(evt);
            }
        });

        jlW1.setText("W:");

        W_UnServidor.setEditable(false);
        W_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        W_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W_UnServidorActionPerformed(evt);
            }
        });

        jlWq1.setText("Wq:");

        Wq_UnServidor.setEditable(false);
        Wq_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        Wq_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wq_UnServidorActionPerformed(evt);
            }
        });

        jlCT1.setText("Costo Anual:");

        jlP01.setText("P0:");

        costoTotal_UnServidor.setEditable(false);
        costoTotal_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        costoTotal_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoTotal_UnServidorActionPerformed(evt);
            }
        });

        p0_UnServidor.setEditable(false);
        p0_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        p0_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p0_UnServidorActionPerformed(evt);
            }
        });

        jlL1.setText("L:");

        jlRho1.setText("Rho:");

        rho_UnServidor.setEditable(false);
        rho_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        rho_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rho_UnServidorActionPerformed(evt);
            }
        });

        costoTotalUnitario_UnServidor.setEditable(false);
        costoTotalUnitario_UnServidor.setPreferredSize(new java.awt.Dimension(90, 25));
        costoTotalUnitario_UnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoTotalUnitario_UnServidorActionPerformed(evt);
            }
        });

        jlCT2.setText("Costo Diario");

        javax.swing.GroupLayout jpPOQ2Layout = new javax.swing.GroupLayout(jpPOQ2);
        jpPOQ2.setLayout(jpPOQ2Layout);
        jpPOQ2Layout.setHorizontalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPOQ2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlW1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLq1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRho1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlP01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCT1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlWq1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCT2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Wq_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(costoTotal_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(W_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lq_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p0_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rho_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoTotalUnitario_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCls1)
                        .addGap(60, 60, 60))))
        );
        jpPOQ2Layout.setVerticalGroup(
            jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlRho1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPOQ2Layout.createSequentialGroup()
                        .addComponent(rho_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p0_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlP01, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlL1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lq_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLq1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(W_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlW1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Wq_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlWq1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoTotal_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPOQ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoTotalUnitario_UnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCT2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnCls1)
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(jSeparator3)
        );

        calcularUnServidor.setText("Calcular");
        calcularUnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularUnServidorActionPerformed(evt);
            }
        });

        jllam1.setText("Lamda:");

        tflam1.setPreferredSize(new java.awt.Dimension(70, 25));
        tflam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflam1ActionPerformed(evt);
            }
        });

        jlmu1.setText("μ:");

        tfmu1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfmu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmu1ActionPerformed(evt);
            }
        });

        jlC_W1.setText("Costo Espera:");

        tfC_W1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC_W1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_W1ActionPerformed(evt);
            }
        });

        jlC_S1.setText("     Costo Servicio:");

        tfC_S1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC_S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_S1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUnServidorLayout = new javax.swing.GroupLayout(pUnServidor);
        pUnServidor.setLayout(pUnServidorLayout);
        pUnServidorLayout.setHorizontalGroup(
            pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUnServidorLayout.createSequentialGroup()
                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUnServidorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUnServidorLayout.createSequentialGroup()
                                .addComponent(jlC_S1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58))
                            .addGroup(pUnServidorLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jllam1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlmu1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlC_W1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfmu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tflam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfC_W1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfC_S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE))
                    .addGroup(pUnServidorLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(calcularUnServidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpPOQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pUnServidorLayout.setVerticalGroup(
            pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPOQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pUnServidorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllam1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmu1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_W1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_W1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUnServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_S1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_S1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(calcularUnServidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mPanel.addTab("UnServidor", pUnServidor);

        btnCalculate4.setText("Calcular");
        btnCalculate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate4ActionPerformed(evt);
            }
        });

        jllam2.setText("Lamda:");

        tflam2.setPreferredSize(new java.awt.Dimension(90, 25));
        tflam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflam2ActionPerformed(evt);
            }
        });

        jlmu2.setText("μ:");

        tfmu2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfmu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmu2ActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tfL2.setEditable(false);
        tfL2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfL2ActionPerformed(evt);
            }
        });

        jlLq2.setText("Lq:");

        tfLq2.setEditable(false);
        tfLq2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfLq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLq2ActionPerformed(evt);
            }
        });

        jlW2.setText("W:");

        tfW2.setEditable(false);
        tfW2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfW2ActionPerformed(evt);
            }
        });

        jlWq2.setText("Wq:");

        tfWq2.setEditable(false);
        tfWq2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfWq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWq2ActionPerformed(evt);
            }
        });

        jlCT4.setText("Costo total:");

        jlP2.setText("P0:");

        tfCT4.setEditable(false);
        tfCT4.setPreferredSize(new java.awt.Dimension(90, 25));
        tfCT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT4ActionPerformed(evt);
            }
        });

        tfP2.setEditable(false);
        tfP2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP2ActionPerformed(evt);
            }
        });

        jlL2.setText("L:");

        jlRho2.setText("Rho:");

        tfRho2.setEditable(false);
        tfRho2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfRho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRho2ActionPerformed(evt);
            }
        });

        tfCET1.setEditable(false);
        tfCET1.setPreferredSize(new java.awt.Dimension(90, 25));
        tfCET1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCET1ActionPerformed(evt);
            }
        });

        jlCET1.setText("C_E_T:");

        tfCST1.setEditable(false);
        tfCST1.setPreferredSize(new java.awt.Dimension(90, 25));
        tfCST1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCST1ActionPerformed(evt);
            }
        });

        jlCST1.setText("C_S_T:");

        javax.swing.GroupLayout jpPOQ5Layout = new javax.swing.GroupLayout(jpPOQ5);
        jpPOQ5.setLayout(jpPOQ5Layout);
        jpPOQ5Layout.setHorizontalGroup(
            jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPOQ5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPOQ5Layout.createSequentialGroup()
                        .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRho2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlP2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlL2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLq2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlW2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlWq2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfLq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfRho2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfWq2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfW2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ5Layout.createSequentialGroup()
                        .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCET1)
                            .addComponent(jlCST1)
                            .addComponent(jlCT4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCST1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCET1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCT4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpPOQ5Layout.setVerticalGroup(
            jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRho2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlL2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLq2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlW2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfW2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlWq2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCET1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCET1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCST1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCST1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpPOQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addComponent(jSeparator6)
        );

        jlC_W2.setText("Costo de Espera");

        tfC_W2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfC_W2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_W2ActionPerformed(evt);
            }
        });

        jlC_S2.setText("Costo de Servicio:");

        tfC_S2.setPreferredSize(new java.awt.Dimension(90, 25));
        tfC_S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_S2ActionPerformed(evt);
            }
        });

        jls.setText("s:");

        tfls1.setPreferredSize(new java.awt.Dimension(90, 25));
        tfls1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfls1ActionPerformed(evt);
            }
        });

        btnCls4.setText("Limpiar");
        btnCls4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCls4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMultiplesServidoresLayout = new javax.swing.GroupLayout(pMultiplesServidores);
        pMultiplesServidores.setLayout(pMultiplesServidoresLayout);
        pMultiplesServidoresLayout.setHorizontalGroup(
            pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMultiplesServidoresLayout.createSequentialGroup()
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                                .addComponent(jlC_S2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                                .addComponent(jlC_W2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                                .addComponent(jls, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jllam2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlmu2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfC_S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfC_W2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfls1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tflam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfmu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMultiplesServidoresLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCls4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPOQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pMultiplesServidoresLayout.setVerticalGroup(
            pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPOQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMultiplesServidoresLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllam2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmu2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jls, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfls1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_W2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_W2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_S2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_S2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMultiplesServidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate4)
                    .addComponent(btnCls4))
                .addGap(15, 15, 15))
        );

        mPanel.addTab("MultiplesServidores", pMultiplesServidores);

        tfN1.setPreferredSize(new java.awt.Dimension(70, 25));
        tfN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfN1ActionPerformed(evt);
            }
        });

        btnCalculate5.setText("Calcular");
        btnCalculate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate5ActionPerformed(evt);
            }
        });

        jllam3.setText("Lamda:");

        tflam3.setPreferredSize(new java.awt.Dimension(70, 25));
        tflam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflam3ActionPerformed(evt);
            }
        });

        jlmu3.setText("     μ:");

        tfmu3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfmu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmu3ActionPerformed(evt);
            }
        });

        jlC_W3.setText("Costo_Servicio.");

        btnCls5.setText("Limpiar");
        btnCls5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCls5ActionPerformed(evt);
            }
        });

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tfL3.setEditable(false);
        tfL3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfL3ActionPerformed(evt);
            }
        });

        jlLq3.setText("Lq:");

        tfLq3.setEditable(false);
        tfLq3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfLq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLq3ActionPerformed(evt);
            }
        });

        jlW3.setText("W:");

        tfW3.setEditable(false);
        tfW3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfW3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfW3ActionPerformed(evt);
            }
        });

        jlWq3.setText("Wq:");

        tfWq3.setEditable(false);
        tfWq3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfWq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWq3ActionPerformed(evt);
            }
        });

        jlCT5.setText("Costo total:");

        jlP3.setText("P0:");

        tfCT5.setEditable(false);
        tfCT5.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCT5ActionPerformed(evt);
            }
        });

        tfP3.setEditable(false);
        tfP3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfP3ActionPerformed(evt);
            }
        });

        jlL3.setText("L:");

        jlRho3.setText("Rho:");

        tfRho3.setEditable(false);
        tfRho3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfRho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRho3ActionPerformed(evt);
            }
        });

        tfCET2.setEditable(false);
        tfCET2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCET2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCET2ActionPerformed(evt);
            }
        });

        jlCET2.setText("C_E_T:");

        tfCST2.setEditable(false);
        tfCST2.setPreferredSize(new java.awt.Dimension(70, 25));
        tfCST2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCST2ActionPerformed(evt);
            }
        });

        jlCST2.setText("C_S_T:");

        javax.swing.GroupLayout jpPOQ6Layout = new javax.swing.GroupLayout(jpPOQ6);
        jpPOQ6.setLayout(jpPOQ6Layout);
        jpPOQ6Layout.setHorizontalGroup(
            jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPOQ6Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ6Layout.createSequentialGroup()
                        .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPOQ6Layout.createSequentialGroup()
                                .addComponent(jlCST2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPOQ6Layout.createSequentialGroup()
                                .addComponent(jlCET2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCET2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPOQ6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfWq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPOQ6Layout.createSequentialGroup()
                                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlP3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlL3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlLq3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlW3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlWq3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPOQ6Layout.createSequentialGroup()
                                .addComponent(jlRho3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfRho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(jpPOQ6Layout.createSequentialGroup()
                        .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPOQ6Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnCls5))
                            .addGroup(jpPOQ6Layout.createSequentialGroup()
                                .addComponent(jlCT5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        jpPOQ6Layout.setVerticalGroup(
            jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPOQ6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRho3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlP3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlL3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLq3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlW3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlWq3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCET2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCET2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCST2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCST2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpPOQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCT5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCls5)
                .addGap(16, 16, 16))
            .addComponent(jSeparator7)
        );

        tfC_W3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC_W3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_W3ActionPerformed(evt);
            }
        });

        jlC_S3.setText("Costo_Espera_Cliente:");

        tfC_S3.setPreferredSize(new java.awt.Dimension(70, 25));
        tfC_S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfC_S3ActionPerformed(evt);
            }
        });

        jlN1.setText("     N:");

        javax.swing.GroupLayout pFuenteFinitaLayout = new javax.swing.GroupLayout(pFuenteFinita);
        pFuenteFinita.setLayout(pFuenteFinitaLayout);
        pFuenteFinitaLayout.setHorizontalGroup(
            pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFuenteFinitaLayout.createSequentialGroup()
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                        .addGap(0, 176, Short.MAX_VALUE)
                        .addComponent(btnCalculate5)
                        .addGap(18, 18, 18))
                    .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                                .addComponent(jlC_W3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfC_W3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                                .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                                    .addComponent(jllam3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tflam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                                    .addComponent(jlmu3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfmu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                                .addComponent(jlC_S3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfC_S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpPOQ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pFuenteFinitaLayout.setVerticalGroup(
            pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPOQ6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFuenteFinitaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jllam3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tflam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmu3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlN1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_W3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_W3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pFuenteFinitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC_S3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfC_S3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculate5)
                .addGap(18, 18, 18))
        );

        mPanel.addTab("FuenteFinita", pFuenteFinita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Var1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Var1ActionPerformed

    private void tfC_S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_S3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_S3ActionPerformed

    private void tfC_W3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_W3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_W3ActionPerformed

    private void tfCST2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCST2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCST2ActionPerformed

    private void tfCET2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCET2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCET2ActionPerformed

    private void tfRho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRho3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRho3ActionPerformed

    private void tfP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP3ActionPerformed

    private void tfCT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT5ActionPerformed

    private void tfWq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWq3ActionPerformed

    private void tfW3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfW3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfW3ActionPerformed

    private void tfLq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLq3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLq3ActionPerformed

    private void tfL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfL3ActionPerformed

    private void btnCls5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCls5ActionPerformed

        tflam3.setText("");
        tfmu3.setText("");
        tfN1.setText("");
        tfC_W3.setText("");
        tfC_S3.setText("");
        tfRho3.setText("");
        tfP3.setText("");
        tfL3.setText("");
        tfLq3.setText("");
        tfW3.setText("");
        tfWq3.setText("");
        tfCET2.setText("");
        tfCST2.setText("");
        tfCT5.setText("");
    }//GEN-LAST:event_btnCls5ActionPerformed

    private void tfmu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmu3ActionPerformed

    private void tflam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflam3ActionPerformed

    private void btnCalculate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate5ActionPerformed

        double lamTx = Double.parseDouble(tflam3.getText());
        double muTx = Double.parseDouble(tfmu3.getText());
        int nTx = Integer.parseInt(tfN1.getText());
        double cwTx = Double.parseDouble(tfC_W3.getText());
        double csTx = Double.parseDouble(tfC_S3.getText());

        FuenteFinita fF = new FuenteFinita(lamTx, muTx, nTx, cwTx, csTx);

        tfRho3.setText("" + dF.format(fF.rho));
        tfP3.setText("" + dF.format(fF.P0));
        tfL3.setText("" + dF.format(fF.L));
        tfLq3.setText("" + dF.format(fF.Lq));
        tfW3.setText("" + dF.format(fF.W));
        tfWq3.setText("" + dF.format(fF.Wq));
        tfCET2.setText("" + dF.format(fF.Costo_Espera_Diario));
        tfCST2.setText("" + dF.format(fF.Costo_Servicio_Diario));
        tfCT5.setText("" + dF.format(fF.Costo_Total));

    }//GEN-LAST:event_btnCalculate5ActionPerformed

    private void tfN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfN1ActionPerformed

    private void tfls1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfls1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfls1ActionPerformed

    private void tfC_S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_S2ActionPerformed

    private void tfC_W2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_W2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_W2ActionPerformed

    private void tfCST1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCST1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCST1ActionPerformed

    private void tfCET1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCET1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCET1ActionPerformed

    private void tfRho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRho2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRho2ActionPerformed

    private void tfP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfP2ActionPerformed

    private void tfCT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCT4ActionPerformed

    private void tfWq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWq2ActionPerformed

    private void tfW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfW2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfW2ActionPerformed

    private void tfLq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLq2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLq2ActionPerformed

    private void tfL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfL2ActionPerformed

    private void btnCls4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCls4ActionPerformed

        tflam2.setText("");
        tfmu2.setText("");
        tfls1.setText("");
        tfC_W2.setText("");
        tfC_S2.setText("");
        tfRho2.setText("");
        tfP2.setText("");
        tfL2.setText("");
        tfLq2.setText("");
        tfW2.setText("");
        tfWq2.setText("");
        tfCET1.setText("");
        tfCST1.setText("");
        tfCT4.setText("");
    }//GEN-LAST:event_btnCls4ActionPerformed

    private void tfmu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmu2ActionPerformed

    private void tflam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflam2ActionPerformed

    private void btnCalculate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate4ActionPerformed

        double lamTx = Double.parseDouble(tflam2.getText());
        double muTx = Double.parseDouble(tfmu2.getText());
        int lsTx = Integer.parseInt(tfls1.getText());
        double cwTx = Double.parseDouble(tfC_W2.getText());
        double csTx = Double.parseDouble(tfC_S2.getText());

        MultiplesServidores mS = new MultiplesServidores(lamTx, muTx, lsTx, cwTx, csTx);

        tfRho2.setText("" + dF.format(mS.rho));
        tfP2.setText("" + dF.format(mS.P0));
        tfL2.setText("" + dF.format(mS.L));
        tfLq2.setText("" + dF.format(mS.Lq));
        tfW2.setText("" + dF.format(mS.W));
        tfWq2.setText("" + dF.format(mS.Wq));
        tfCET1.setText("" + dF.format(mS.costoEsperaDiario));
        tfCST1.setText("" + dF.format(mS.costoServicioDiario));
        tfCT4.setText("" + dF.format(mS.costoAnual));
    }//GEN-LAST:event_btnCalculate4ActionPerformed

    private void tfC_S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_S1ActionPerformed

    private void tfC_W1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfC_W1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfC_W1ActionPerformed

    private void tfmu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmu1ActionPerformed

    private void tflam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflam1ActionPerformed

    private void calcularUnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularUnServidorActionPerformed

        double lam = Double.parseDouble(tflam1.getText());
        double miu = Double.parseDouble(tfmu1.getText());
        double costoEspera = Double.parseDouble(tfC_W1.getText());
        double costoServicio = Double.parseDouble(tfC_S1.getText());

        UnServidor unServidor = new UnServidor(lam, miu, costoEspera, costoServicio);

        rho_UnServidor.setText("" + dF.format(unServidor.getRho()));
        p0_UnServidor.setText("" + dF.format(unServidor.getP0()));
        L_UnServidor.setText("" + dF.format(unServidor.getL()));
        Lq_UnServidor.setText("" + dF.format(unServidor.getLq()));
        W_UnServidor.setText("" + dF.format(unServidor.getW()));
        Wq_UnServidor.setText("" + dF.format(unServidor.getWq()));
        costoTotal_UnServidor.setText("" + dF.format(unServidor.getCostoAnual()));
        costoTotalUnitario_UnServidor.setText("" + dF.format(unServidor.getCostoDiario()));
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularUnServidorActionPerformed

    private void rho_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rho_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rho_UnServidorActionPerformed

    private void p0_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p0_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p0_UnServidorActionPerformed

    private void costoTotal_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoTotal_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoTotal_UnServidorActionPerformed

    private void Wq_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wq_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Wq_UnServidorActionPerformed

    private void W_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W_UnServidorActionPerformed

    private void Lq_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lq_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lq_UnServidorActionPerformed

    private void L_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_UnServidorActionPerformed

    private void btnCls1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCls1ActionPerformed

        tflam1.setText("");
        tfmu1.setText("");
        tfC_W1.setText("");
        tfC_S1.setText("");
        rho_UnServidor.setText("");
        p0_UnServidor.setText("");
        L_UnServidor.setText("");
        Lq_UnServidor.setText("");
        W_UnServidor.setText("");
        Wq_UnServidor.setText("");
        costoTotal_UnServidor.setText("");
        costoTotalUnitario_UnServidor.setText("");
    }//GEN-LAST:event_btnCls1ActionPerformed

    private void costoTotalUnitario_UnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoTotalUnitario_UnServidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoTotalUnitario_UnServidorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L_UnServidor;
    private javax.swing.JTextField Lq_UnServidor;
    private javax.swing.JTextField W_UnServidor;
    private javax.swing.JTextField Wq_UnServidor;
    private javax.swing.JButton btnCalculate4;
    private javax.swing.JButton btnCalculate5;
    private javax.swing.JButton btnCls1;
    private javax.swing.JButton btnCls4;
    private javax.swing.JButton btnCls5;
    private javax.swing.JButton calcularUnServidor;
    private javax.swing.JTextField costoTotalUnitario_UnServidor;
    private javax.swing.JTextField costoTotal_UnServidor;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jlCET1;
    private javax.swing.JLabel jlCET2;
    private javax.swing.JLabel jlCST1;
    private javax.swing.JLabel jlCST2;
    private javax.swing.JLabel jlCT1;
    private javax.swing.JLabel jlCT2;
    private javax.swing.JLabel jlCT4;
    private javax.swing.JLabel jlCT5;
    private javax.swing.JLabel jlC_S1;
    private javax.swing.JLabel jlC_S2;
    private javax.swing.JLabel jlC_S3;
    private javax.swing.JLabel jlC_W1;
    private javax.swing.JLabel jlC_W2;
    private javax.swing.JLabel jlC_W3;
    private javax.swing.JLabel jlL1;
    private javax.swing.JLabel jlL2;
    private javax.swing.JLabel jlL3;
    private javax.swing.JLabel jlLq1;
    private javax.swing.JLabel jlLq2;
    private javax.swing.JLabel jlLq3;
    private javax.swing.JLabel jlN1;
    private javax.swing.JLabel jlP01;
    private javax.swing.JLabel jlP2;
    private javax.swing.JLabel jlP3;
    private javax.swing.JLabel jlRho1;
    private javax.swing.JLabel jlRho2;
    private javax.swing.JLabel jlRho3;
    private javax.swing.JLabel jlW1;
    private javax.swing.JLabel jlW2;
    private javax.swing.JLabel jlW3;
    private javax.swing.JLabel jlWq1;
    private javax.swing.JLabel jlWq2;
    private javax.swing.JLabel jlWq3;
    private javax.swing.JLabel jllam1;
    private javax.swing.JLabel jllam2;
    private javax.swing.JLabel jllam3;
    private javax.swing.JLabel jlmu1;
    private javax.swing.JLabel jlmu2;
    private javax.swing.JLabel jlmu3;
    private javax.swing.JLabel jls;
    private javax.swing.JPanel jpPOQ2;
    private javax.swing.JPanel jpPOQ5;
    private javax.swing.JPanel jpPOQ6;
    private javax.swing.JTabbedPane mPanel;
    private javax.swing.JTextField p0_UnServidor;
    private javax.swing.JPanel pFuenteFinita;
    private javax.swing.JPanel pMultiplesServidores;
    private javax.swing.JPanel pUnServidor;
    private javax.swing.JTextField rho_UnServidor;
    private javax.swing.JTextField tfCET1;
    private javax.swing.JTextField tfCET2;
    private javax.swing.JTextField tfCST1;
    private javax.swing.JTextField tfCST2;
    private javax.swing.JTextField tfCT4;
    private javax.swing.JTextField tfCT5;
    private javax.swing.JTextField tfC_S1;
    private javax.swing.JTextField tfC_S2;
    private javax.swing.JTextField tfC_S3;
    private javax.swing.JTextField tfC_W1;
    private javax.swing.JTextField tfC_W2;
    private javax.swing.JTextField tfC_W3;
    private javax.swing.JTextField tfL2;
    private javax.swing.JTextField tfL3;
    private javax.swing.JTextField tfLq2;
    private javax.swing.JTextField tfLq3;
    private javax.swing.JTextField tfN1;
    private javax.swing.JTextField tfP2;
    private javax.swing.JTextField tfP3;
    private javax.swing.JTextField tfRho2;
    private javax.swing.JTextField tfRho3;
    private javax.swing.JTextField tfW2;
    private javax.swing.JTextField tfW3;
    private javax.swing.JTextField tfWq2;
    private javax.swing.JTextField tfWq3;
    private javax.swing.JTextField tflam1;
    private javax.swing.JTextField tflam2;
    private javax.swing.JTextField tflam3;
    private javax.swing.JTextField tfls1;
    private javax.swing.JTextField tfmu1;
    private javax.swing.JTextField tfmu2;
    private javax.swing.JTextField tfmu3;
    // End of variables declaration//GEN-END:variables
}
